services:
  - type: web
    name: flickfinda
    env: python
    buildCommand: pip install -r requirements.txt && cd frontend && npm install && npm run build
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --chdir src/movie_app
    envVars:
      - key: OMDB_API_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: YOUTUBE_API_KEY
        sync: false
